### ISSUE TITLE
Dropout rate and other parameters are all set to 0

### ISSUE THREAD

**Issue by Mahmood1968** [dell-ai-engineering/BigDL-ImageProcessing-Examples#11]
I think , these highlighted parameters must be set to certain values. For example , why the default value of maxDropPercentage is 0 ?   I know Resnet and Densenet has dropout layers and these layers should be set to a certain value but when i run analytics zoo only learning rate is set to 0,0005 because I already initialize it . Please can you explain that       
       learningRate: 5.0E-4
	computeThresholdbatchSize: 100
	**maxDropPercentage: 0.0**
	**learningRateDecay: 0.0**
	warmupIterationNum: 200
	isLayerwiseScaled: false
	**dropPercentage: 0.0**

**Comment by balacs13** [comment]
No need to set these values for transfer learing.
