### ISSUE TITLE
Code snapshot all AUC not shown in Jupoyter out console 

### ISSUE THREAD

**Issue by Mahmood1968** [dell-ai-engineering/BigDL-ImageProcessing-Examples#3]
The snaphot that give here 
![jupyter auc](https://user-images.githubusercontent.com/24418838/46893665-55095c00-ce37-11e8-92df-8803203aa143.jpg)
shows mostly 99% for most of the classes  except the last one was very small  while in this snapshot of AUC function 
![auc_functions](https://user-images.githubusercontent.com/24418838/46893699-736f5780-ce37-11e8-8da4-7700b5007ffa.jpg)
There are 20 rows but we have only 15 classes ,, what are these values for

**Comment by balacs13** [comment]
@Mahmood1968 - Is this closed? Can you please add comments and close it, if we are good with this.

**Comment by Mahmood1968** [comment]
Yes this is done by Intel
